### ISSUE TITLE
Support for commas in complex linetype text

### ISSUE THREAD

**Issue by woods-20** [haplokuon/netDxf#210] opened 2020-09-03 09:07 UTC
Hi there,

I'm not familiar with the detailed specificiation for .lin files, but I feel that the linetype load function should support commas in the linetype text for complex text-type linetypes.

We are using netDxf to export ground contours, and if there are half metres these should be shown as "19,5m" for example, if the user's culture settings use commas as decimal seperators.

This fails because the following line in `ReadLineTypeComplexSegment `will split at commas even if they are contained in quotation marks:

`string[] tokens = data.Split(',');`

In my version I have replaced that with the following:

`string[] tokens = System.Text.RegularExpressions.Regex.Split(data, ",(?=(?:[^\"]*\"[^\"]*\")*[^\"]*$)");`

I'm not experienced with regex, but this is something I found on the internet that will apparently split at commas, only when they are not contained in quotation marks, and it seems to resolve this issue.

Thanks for all the work on this project.

**Comment by haplokuon** [comment] 2020-09-04 17:51
This is a bug, and the problem is exactly that. In the LIN file the data is stored separated by commas, but splitting, indiscriminately, the data by the commas will also split the text in LinetypeTextSegments if they contain commas.

If that regular expression does that it will work just fine. I just know the basics about them, and the patterns can get very complex.

**Comment by haplokuon** [comment] 2020-12-06 08:10
Resolved in 2.4.1

**Closed by haplokuon** 2020-12-06 08:10 UTC
Labels: bug
