### ISSUE TITLE
The outputstream.Position does not exist

### ISSUE THREAD

**Issue by Yahasana** [haplokuon/netDxf#4] opened 2017-10-13 14:32 UTC
https://github.com/haplokuon/netDxf/blob/40601825513b5096604122c23edb12ea7a4fcd93/netDxf/IO/DxfWriter.cs#L392

e.g. `dxfDoc.write(context.Response.OutputStream)` will raise this error

EDIT: I add a parameter `public void Write(Stream stream, DxfDocument document, bool binary, bool isRewind = true)` and `if (isRewind) stream.Position = 0;`

no rewind need for outputstream `dxfDoc.write(context.Response.OutputStream, false, false)`

**Comment by haplokuon** [comment] 2017-11-03 08:54
You should be able to delete that line safely, it is not really needed. Some leftover, I guess, I didn't have any issues with it, and I forgot to delete it.

In the DxfReader class there are a couple of lines like that "stream.Position = 0;", they are there for convenience. You can check a few things of the dxf without having to read the whole thing. Like checking is it is binary or a header variable, and rewinding the stream is needed in those cases.

I should let the caller of the methods that use it decide if it is needed. Since they are the responsibility of properly handling the stream is the caller not the method; just like the caller is the responsible of disposing it.

Daniel

**Comment by haplokuon** [comment] 2017-11-28 16:46
Fixed in [2017/11/28]. Even thought I have not been able to reproduce the problem, but being able to control the stream position will give you some more flexibility.

**Closed by haplokuon** 2017-11-28 16:46 UTC
Labels: bug
